version: 0.2
        
phases:
  install:
    commands:
      #- python -m venv book-api               sudo yum install python3.11  / python3.11 -m venv book-api
      #- source book-api/bin/activate          source book-api/bin/activate
      #- pip install --upgrade pip             sudo yum install pip
      #                                        pip install --upgrade pip
      #- pip install Django==4.2.7             pip install Django==4.2.7
      #- pip install djangorestframework       pip install djangorestframework
      #- pip install django-filter             pip install django-filter
      #- pip install djangorestframework_simplejwt  pip install djangorestframework_simplejwt
      #- pip install django-money              pip install django-money
      #- pip install markdown                  pip install markdown
      #- pip install Pillow                    pip install Pillow
      #- pip install mysql-connector-python    pip install mysql-connector-python==8.0.29
      #- yum -y install pkgconfig
      #- export MYSQLCLIENT_CFLAGS='pkg-config mysqlclient --cflags'
      #- export MYSQLCLIENT_LDFLAGS='pkg-config mysqlclient --libs'
      #- pip install mysqlclient --no-cache-dir
      #- yum -y install mariadb

  build:
    commands:
      #- cp 
      #mysql -h books.c5ktsotgokwo.us-east-2.rds.amazonaws.com -P 3306 -u admin -ppassword Password$12
      
      # sudo dnf install mariadb105

      # mysql -h books.c5ktsotgokwo.us-east-2.rds.amazonaws.com -P 3306 -u admin -p
       
      # create database books;
       
      # python manage.py makemigrations
       
      # python manage.py migrate
       
       
       
       
      #- export DJANGO_SUPERUSER_USERNAME=admin
      #- export DJANGO_SUPERUSER_EMAIL=mfriha@hotmail.com
      #- export DJANGO_SUPERUSER_PASSWORD=Password$12    
      #- python manage.py createsuperuser --no-input  (do manual) 
      
      #  Edit settings.py of your django app, set ALLOWED_HOSTS to = ["*"]
      #  python manage.py runserver 0:8000 
        
      #  ec2-3-16-113-191.us-east-2.compute.amazonaws.com
        
      #  http://ec2-3-16-113-191.us-east-2.compute.amazonaws.com:8000/api/books
      #  http://ec2-3-16-113-191.us-east-2.compute.amazonaws.com:8000/api/books/3
      #  http://ec2-3-16-113-191.us-east-2.compute.amazonaws.com:8000/api/books/3/reviews

artifacts:
  files:
    #- 'target/bookstore'
    #- 'appspec.yml' 
    #- 'scripts/before_install.sh'
    #- 'scripts/after_install.sh'
    #- 'scripts/start_server.sh'
    #- 'scripts/stop_server.sh' 
    - '*.*'   
     
      
      
      
      
      
