version: 0.2
        
phases:
  install:
    commands:
      - python -m venv book-api
      - source book-api/bin/activate
      - pip install --upgrade pip
      - pip install Django==4.2.7
      - pip install djangorestframework
      - pip install django-filter
      - pip install djangorestframework_simplejwt
      - pip install django-money
      - pip install markdown
      - pip install Pillow
      #yum -y install mariadb
      - apt-get install python-mysqldb

  build:
    commands:
      #mysql -h books.c5ktsotgokwo.us-east-2.rds.amazonaws.com -P 3306 -u admin -ppassword Password$12
      - export DJANGO_SUPERUSER_USERNAME=admin
      - export DJANGO_SUPERUSER_EMAIL=mfriha@hotmail.com
      - export DJANGO_SUPERUSER_PASSWORD=Password$12
      - python manage.py createsuperuser --no-input
      - python manage.py makemigrations
      - python manage.py migrate
      
      
      
      
      
